# Generated by Django 4.1.5 on 2023-01-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_cart_cartitem_delete_formation_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realisation',
            name='categorie',
        ),
        migrations.AddField(
            model_name='product',
            name='categorie',
            field=models.ManyToManyField(related_name='categorie', to='myapp.categorie'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
