# Generated by Django 4.1.5 on 2023-02-02 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_brand_color_tag_product_brand_product_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='categorie',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='statut',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='nom',
            new_name='name',
        ),
    ]
