# Generated by Django 4.1.5 on 2023-02-02 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_nom_brand_name_rename_nom_categorie_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Realisation',
        ),
    ]
