# Generated by Django 4.1.5 on 2023-02-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Blog')),
                ('description', models.TextField(blank=True)),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('categorie', models.ManyToManyField(related_name='categorie1', to='myapp.categorie')),
            ],
        ),
        migrations.DeleteModel(
            name='Blogs',
        ),
    ]
